language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jmendo19/docker-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true  jmendo19/docker-playground npm run test
